Ready for Review
Fidesnoella/the-gym-kmarkter pull request #1
Opened 2022-10-05 21:25 UTC by Fidesnoella

2022-10-06 09:02 UTC, alain-kubwayo requested changes
### Good job applying BEM
Refer to the comments on areas of improvement.

2022-10-06 09:02 UTC, alain-kubwayo commented on index.html
> +                    <h5 class="card-item card-item--title">Legal</h5>
Same here.

2022-10-06 09:02 UTC, alain-kubwayo commented on index.html
> +                    <h5 class="card-item card-item--title">Resources</h5>
Here too.

2022-10-06 09:02 UTC, alain-kubwayo commented on index.html
> +                <h5 class="card-item card-item--title">Get In Touch</h5>
And here.

2022-10-06 09:02 UTC, alain-kubwayo commented on index.html
> +                <p class="subscribe-content__paragraph">Lorem impsum dolor amit</p>
`paragraph` isn't a good name. `description` or similar name sounds much better.

2022-10-07 10:15 UTC, alain-kubwayo requested changes
### Good job implementing the reviews.
Just minor adjustments to go.

2022-10-07 10:15 UTC, alain-kubwayo commented on index.html
> +                <h5 class="title title--small title--white">Get In Touch</h5>
`title-white` doesn't sound  like a good BEM name. Use something a little more generic so you don't have to change it in both HTML and CSS in case white changes to blue for instance. something like `title__light` or `title__primary`, etc.  You can adjust it in other footer areas  where you are using `title-white` as well.

2022-10-07 10:53 UTC, alain-kubwayo approved these changes
### Good job!

2022-10-07 10:59 UTC, Nkaka23dev approved these changes

2022-10-07 13:02 UTC, karemarsy requested changes

2022-10-07 13:02 UTC, karemarsy commented on index.html
> +                <p class="subscribe-content__description">Lorem impsum dolor amit</p>
`subscribe-content__description` is positioned outside the Block (subscribe-content).

2022-10-19 10:27 UTC, karemarsy reviewed
@Fidesnoella you should also ready this notion https://www.notion.so/musayann/BEM-reviews-highlights-0d16ab192f134555a6f9ecf64a230498

2022-10-19 10:27 UTC, karemarsy approved these changes

2022-10-25 07:35 UTC, merged